### PR TITLE
#135: added support for lists in map

### LINKED ISSUE #135: Support lists in map
It would be nice if we could support list in maps like:

```
Chat:
  path: webservice/chat
  properties:
    name: String
    id: String
    unreadMessages: Map<String, List<String>>
```

### PR DESCRIPTION
**Pull request by jorre127**
fixes #135

### CODE REVIEW

**Review by vanlooverenkoen — DISMISSED** [review]
where are your tests?

**Comment by vanlooverenkoen** [comment]
add docs

**Comment by vanlooverenkoen** [comment]
Add this to example/config.yaml

```
ProjectWrapper:
  path: user/project/
  type: object
  properties:
    projectListById:
      type: Map<String, List<Person>>
```

**Comment by jorre127** [comment]
> Add this to example/config.yaml
> 
> ```
> ProjectWrapper:
>   path: user/project/
>   type: object
>   properties:
>     projectListById:
>       type: Map<String, List<Person>>
> ```

Fixed in next PR

**Review by ikbendewilliam — APPROVED** [review]

**Review by ikbendewilliam — CHANGES_REQUESTED** [review]
Please improve error handling when updating from older version. Old Enums show this error 
```
Unhandled exception:
type 'Null' is not a subtype of type 'String'
#0      new YmlGeneratorConfig.<anonymous closure>.<anonymous closure> (package:model_generator/config/yml_generator_config.dart:124:13)
#1      MapBase.forEach (dart:collection/maps.dart:35:13)
#2      new YmlGeneratorConfig.<anonymous closure> (package:model_generator/config/yml_generator_config.dart:115:21)
#3      MapBase.forEach (dart:collection/maps.dart:35:13)
#4      new YmlGeneratorConfig (package:model_generator/config/yml_generator_config.dart:35:17)
#5      ModelGenerator.generate (package:model_generator/main.dart:57:11)
```

**Comment by ikbendewilliam** [comment]
Maybe we should also allow short notations for enums?
```yaml
Gender:
  type: enum
  values:
    MALE: male
    FEMALE: femAle
    other: other
    X: x
```

**Comment by ikbendewilliam** [comment]
```yaml
    vehicleFull:
      json_value: VEHICLE_FULL
```
results in a lowecase jsonValue
`@JsonValue('vehicleFull')`
Why would we change the capitalization from the jsonValue?

**Review by ikbendewilliam — APPROVED** [review]

**Pull request merged**
